DROP TABLE IF EXISTS book;

CREATE TABLE book(
    id BIGSERIAL PRIMARY KEY NOT NULL,
    author VARCHAR(255) NOT NULL,
    isbn VARCHAR(255) NOT NULL,
    price FLOAT NOT NULL,
    title VARCHAR NOT NULL,
    version INTEGER NOT NULL
);